### PR TITLE
News component

### PR DESCRIPTION
**Pull request by guyinjeans**

### CODE REVIEW

**Comment by jenniferwg** [comment]
Please change these aspects before requesting a merge: 
* ensure all state and country data displays correctly after these changes
* no obvious map change (the background color for the states/countries should not change)

Thanks!

**Comment by guyinjeans** [comment]
Yes boss

**Comment by guyinjeans** [comment]
Done possibly.

**Comment by guyinjeans** [comment]
Css fixed

**Comment by guyinjeans** [comment]
Css more fixed

**Pull request merged**
